export {}; // Make this a module

declare global {
  interface Verse {
    id: number;
    text: string;
    reference: string | null;
    tags: string | null;
    created_at: string;
    updated_at: string;
  }

  interface World {
    id: number;
    name: string;
    thumbnail: string | null;
    short_description: string | null;
    last_viewed_at: string | null;
    created_at: string;
    updated_at: string;
  }

  interface Level {
    id: number;
    world_id: number;
    name: string;
    category: string;
    description: string | null;
    created_at: string;
    updated_at: string;
  }

  interface DbApi {
    verses: {
      getAll(): Promise<Verse[]>;
      add(data: {
        text: string;
        reference?: string;
        tags?: string;
      }): Promise<Verse>;
      update(
        id: number,
        data: { text?: string; reference?: string; tags?: string },
      ): Promise<Verse>;
      delete(id: number): Promise<{ id: number }>;
    };
    worlds: {
      getAll(): Promise<World[]>;
      getById(id: number): Promise<World | null>;
      add(data: {
        name: string;
        thumbnail?: string | null;
        short_description?: string | null;
      }): Promise<World>;
      update(
        id: number,
        data: {
          name?: string;
          thumbnail?: string | null;
          short_description?: string | null;
        },
      ): Promise<World>;
      delete(id: number): Promise<{ id: number }>;
      markViewed(id: number): Promise<World>;
    };
    levels: {
      getAllByWorld(worldId: number): Promise<Level[]>;
      getById(id: number): Promise<Level | null>;
      add(data: {
        world_id: number;
        name: string;
        category: string;
        description?: string | null;
      }): Promise<Level>;
      update(
        id: number,
        data: { name?: string; category?: string; description?: string | null },
      ): Promise<Level>;
      delete(id: number): Promise<{ id: number }>;
    };
  }

  interface Window {
    db: DbApi;
  }
  // This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
  // plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
  // whether you're running in development or production).
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  namespace NodeJS {
    interface Process {
      // Used for hot reload after preload scripts.
      viteDevServers: Record<string, import('vite').ViteDevServer>;
    }
  }

  type VitePluginConfig = ConstructorParameters<
    typeof import('@electron-forge/plugin-vite').VitePlugin
  >[0];

  interface VitePluginRuntimeKeys {
    VITE_DEV_SERVER_URL: `${string}_VITE_DEV_SERVER_URL`;
    VITE_NAME: `${string}_VITE_NAME`;
  }
}

declare module 'vite' {
  interface ConfigEnv<
    K extends keyof VitePluginConfig = keyof VitePluginConfig,
  > {
    root: string;
    forgeConfig: VitePluginConfig;
    forgeConfigSelf: VitePluginConfig[K][number];
  }
}
